### ISSUE TITLE
Issue with setcolumns() method

### ISSUE THREAD

**Issue by moudarir** [n1crack/datatables-examples#1]
Hi,

**This is my query**
```sql
SELECT `nl`.`id`, `nl`.`id` AS `item_id`, `nl`.`title`, `nl`.`from_group`, `nl`.`destination_group`, `nl`.`section`, `nl`.`action`, CONCAT(`u`.`first_name`, ' ', UPPER(`u`.`last_name`)) AS `user_name`, `nl`.`status`
FROM `notification_lists` AS `nl`
INNER JOIN `users` AS `u` ON `nl`.`user_id` = `u`.`id`
GROUP BY `nl`.`id`
ORDER BY `nl`.`created_at` DESC
```
If i use this code with your library it return an error

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from (SELECT `nl`.`id`, `nl`.`id` AS `item_id`, `nl`.`title`, `nl`.`from_group`,' at line 1
> 
> Select count(*) as rowcount from (Select id, item_id, title, from (SELECT `nl`.`id`, `nl`.`id` AS `item_id`, `nl`.`title`, `nl`.`from_group`, `nl`.`destination_group`, `nl`.`section`, `nl`.`action`, CONCAT(`u`.`first_name`, ' ', UPPER(`u`.`last_name`)) AS `user_name`, `nl`.`status` FROM `notification_lists` AS `nl` INNER JOIN `users` AS `u` ON `nl`.`user_id` = `u`.`id` GROUP BY `nl`.`id` ORDER BY `nl`.`created_at` DESC)t)t

But in phpMyAdmin it's work perfectly.

I used "**from_group**" in my Query which have "**_from_**" string. If i remove them then it's work.

I inspert this from your setcolumns() method in "Datatables" Class
```php
$query = preg_replace("/\((?:[^()]+|(?R))*+\)/i", "", $query);
        preg_match_all("/SELECT([\s\S]*?)((\s*)FROM(?![\s\S]*\)))([\s\S]*?)/i", $query, $columns);
```

Thanks in advance for your help and sorry about my bad language.

**Comment by n1crack** [comment]
I am not at home now. Can you try this code? 

$query = preg_replace("/\((?:[^()]+|(?R))*+\)/i", "", $query);
        preg_match_all("/SELECT([\s\S]*?)((\s*)\bFROM\b(?![\s\S]*\)))([\s\S]*?)/i", $query, $columns);

*sent from mobile

**Comment by moudarir** [comment]
Yep,
it's work with this

```php
// line number : 143
preg_match_all("/SELECT([\s\S]*?)((\s*)\bFROM\b(?![\s\S]*\)))([\s\S]*?)/i", $query, $columns);
```
Thank you

**Comment by n1crack** [comment]
updated the library. 

thank you
